"""
Report Generation Service
"""

from typing import Optional
from io import BytesIO
from datetime import datetime


class ReportService:
    """Service for generating PDF reports"""
    
    def generate_report(
        self,
        analysis_data: dict,
        user_name: Optional[str] = None,
    ) -> bytes:
        """
        Generate a PDF report from analysis data
        
        In production, use reportlab or weasyprint for PDF generation.
        This returns a simple text-based report for demo purposes.
        """
        report_content = self._build_report_content(analysis_data, user_name)
        return report_content.encode("utf-8")
    
    def _build_report_content(
        self,
        data: dict,
        user_name: Optional[str] = None,
    ) -> str:
        """Build report content as formatted text"""
        
        name = user_name or "Candidate"
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        report = f"""
================================================================================
                    AI CAREER ASSISTANT - RESUME ANALYSIS REPORT
================================================================================

Generated for: {name}
Date: {timestamp}

--------------------------------------------------------------------------------
                              OVERALL SCORES
--------------------------------------------------------------------------------

Overall Score:        {data.get('overallScore', 0)}%
ATS Compatibility:    {data.get('atsScore', 0)}%
Keyword Match:        {data.get('keywordScore', 0)}%
Format Score:         {data.get('formatScore', 0)}%
Content Quality:      {data.get('contentScore', 0)}%

Verdict: {data.get('verdict', 'N/A')}

--------------------------------------------------------------------------------
                           SECTION-BY-SECTION FEEDBACK
--------------------------------------------------------------------------------
"""
        
        sections = data.get("sections", [])
        for section in sections:
            report += f"""
{section.get('name', 'Section').upper()}
Score: {section.get('score', 0)}%
Status: {section.get('status', 'N/A')}
Feedback: {section.get('feedback', 'No feedback available')}
"""
        
        report += """
--------------------------------------------------------------------------------
                            MATCHED KEYWORDS
--------------------------------------------------------------------------------
"""
        
        keywords = data.get("keywords", [])
        if keywords:
            keyword_str = ", ".join(keywords[:20])
            report += f"\n{keyword_str}\n"
        else:
            report += "\nNo keywords matched.\n"
        
        report += """
--------------------------------------------------------------------------------
                         IMPROVEMENT SUGGESTIONS
--------------------------------------------------------------------------------
"""
        
        improvements = data.get("improvements", [])
        for i, improvement in enumerate(improvements, 1):
            report += f"""
{i}. [{improvement.get('priority', 'medium').upper()}] {improvement.get('title', 'Improvement')}
   Category: {improvement.get('category', 'General')}
   {improvement.get('description', 'No description')}
"""
        
        report += """
--------------------------------------------------------------------------------
                              NEXT STEPS
--------------------------------------------------------------------------------

1. Address high-priority improvements first
2. Update your resume with the suggested keywords
3. Ensure consistent formatting throughout
4. Quantify achievements with metrics where possible
5. Tailor your resume for each specific job application

================================================================================
            Report generated by AI Career Assistant - www.example.com
================================================================================
"""
        
        return report
    
    def generate_skills_gap_report(
        self,
        skills_data: dict,
        user_name: Optional[str] = None,
    ) -> bytes:
        """Generate a skills gap analysis report"""
        
        name = user_name or "Candidate"
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        report = f"""
================================================================================
                    AI CAREER ASSISTANT - SKILLS GAP REPORT
================================================================================

Generated for: {name}
Date: {timestamp}
Target Role: {skills_data.get('targetRole', 'N/A')}

--------------------------------------------------------------------------------
                              READINESS SCORE
--------------------------------------------------------------------------------

Overall Readiness: {skills_data.get('readinessScore', 0)}%

--------------------------------------------------------------------------------
                              SKILL GAPS
--------------------------------------------------------------------------------
"""
        
        gaps = skills_data.get("gaps", [])
        for gap in gaps:
            report += f"""
{gap.get('skill', 'Skill')}
  Current Level: {gap.get('currentLevel', 0)}%
  Required Level: {gap.get('requiredLevel', 0)}%
  Gap: {gap.get('gap', 0)}%
  Importance: {gap.get('importance', 'medium')}
"""
        
        report += """
--------------------------------------------------------------------------------
                            90-DAY ROADMAP
--------------------------------------------------------------------------------
"""
        
        roadmap = skills_data.get("roadmap", [])
        for phase in roadmap:
            report += f"""
{phase.get('phase', 'Phase')} ({phase.get('duration', 'N/A')})
Focus: {phase.get('focus', 'N/A')}
Goals:
"""
            for goal in phase.get("goals", []):
                report += f"  - {goal}\n"
            
            report += "Resources:\n"
            for resource in phase.get("resources", []):
                report += f"  - {resource.get('name', 'Resource')} ({resource.get('type', 'course')}) - {resource.get('platform', 'Online')}\n"
        
        report += """
================================================================================
            Report generated by AI Career Assistant - www.example.com
================================================================================
"""
        
        return report.encode("utf-8")
